---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Nan-Hung Hsieh 
orcid:  "orcid.org/0000-0003-0163-2766"
jobtitle: "Postdoctoral Research Associate, Texas A&M University"
#address: "402 Raymond Stotzer Pkwy, College Station, TX 77845"
fontawesome: yes
email: nhsieh@cvm.tamu.edu
github: nanhung
#phone: "+1 555 5555"
web: nanhung.rbind.io
updated: yes

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# EXPERIENCE
Department of Veterinary Integrative Biosciences, Texas A&M University  
Postdoctoral Research Associate  \hfill 08/2016 --

\hfill Supervisor: Prof. [Weihsueh A. Chiu](http://vetmed.tamu.edu/vibs/directorydetail?userid=13388)

Division of Occupational Hazards Assessment, Institute of Labor, Occupational Safety and
Health  
Research Associate \hfill 08/2013 -- 07/2016 

# EDUCATION

Ph.D. Bioenvironmental Systems Engineering, National Taiwan University, 2013  

> Dissertation: *Dynamic modeling and analysis of air pollution-associated lung function exacerbations risk* 

\hfill Advisor: Prof. [Chung-Min Liao](http://homepage.ntu.edu.tw/~cmliao/)

M.Eng. Bioenvironmental Systems Engineering, National Taiwan University, 2010  
B.Sc. Safety, Health and Environmental Engineering, National United University, 2007  

# RESEARCH PROJECT
**Postdoctoral Research Associate** \hfill 09/2016--  

> U.S. Food and Drug Administration. *Enhancing the reliability, efficiency, and
usability of Bayesian population PBPK modeling - Create, implement, and evaluate a robust Global
Sensitivity Analysis algorithm to reduce PBPK model parameter dimensionality*. 1U01FD005838-01. 

**Principle Investigator**  \hfill 03/2015--12/2015  

> Institute of Labor, Occupational Safety and Health. *Assessing the Fine Particles-Associated Exposure Hazards for Workers in Workplace*. ILOSH104-A310. 

**Principle Investigator**  \hfill 03/2014--12/2014  

> Institute of Labor, Occupational Safety and Health. *Assessing Health Risks for Workers in High Lead Exposed Factories*. ILOSH103-A307.

# AWARDS
- Outstanding R&D alternative military award, Taiwan Ministry of the Interior, 2016
- Outstanding Alumni, National United University, 2015
- Best PhD Academic Research Paper, National Taiwan University, 2012

# SERVICES TO THE PROFESSION

## Peer review for scientific journals  

- Computational and Mathematical Methods in Medicine (7) 
- Computational Toxicology (1)
- Environmental Research (1)
- International Journal of Environmental Research and Public Health (5)
- International Journal of Molecular Sciences (1)
- International Journal of Occupational and Environmental Health (1)
- Journal of Open Source Software (1)
- European Journal of Pharmaceutical Sciences (1)
- Science of the Total Environment (1)
- Stochastic Environmental Research and Risk Assessment (1)
- Sustainability (1)
- Toxicological Sciences (1)

# COMPUTER INTERESTS

- Operating System: GNU/Linux, MacOS, Windows
- Scientific computing: C, R, Python, MATLAB
- Other: GNU MCSim, Git, High-Performance Computer

# OTHER
- Membership: Society of Toxicology (USA)
- Language: Mandarin (Native), English
- Personal Interests: Computer & Information Technology

---

# PUBLICATIONS

## Software Product

> **Hsieh NH**, Reisfeld B, Chiu WA. pksensi: Global Sensitivity Analysis in Pharmacokinetic Modeling. R package. [[CRAN](https://cran.r-project.org/web/packages/pksensi/index.html)] [[GitHub](https://github.com/nanhung/pksensi)]

## Journal Article 
2018

> Luo YS, **Hsieh NH**, Chiu WA, Rusyn I*. Comparative analysis of metabolism of trichloroethylene and tetrachloroethylene among tissues and mouse strains. Toxicology 2018 Nov; 409(1): 33-43.

> Blanchette AD, Grimm FA, Dalaijamts C, **Hsieh NH**, Ferguson K, Luo YS, Rusyn I, Chiu WA. Thorough QT/QTc in a dish: an in vitro human model that accurately predicts clinical concentration-QTc relationships. Clinical Pharmacology & Therapeutics 2018 Oct; doi: 10.1002/cpt.1259.

> Grimm FA, Blanchette A, House JS, Ferguson K, **Hsieh NH**, Dalaijamts C, Wright AA, Anson B, Wright FA, Chiu WA, Rusyn I\*. A human population-based organotypic *in vitro* model for cardiotoxicity screening. ALTEX 2018 Oct; 35(4): 441-52.   

> Cheng YH, Lin YJ, Chen SC&ast;, You SH, Chen WY, **Hsieh NH**, Yang YF, Liao CM&ast. Assessing health burden risk and control effect on dengue fever infection in southern region of Taiwan. Infection and Drug Resistance 2018 Sep; 11: 1423-35. 

> **Hsieh NH**, Reisfeld B, Bois FY, Chiu WA*. Applying a global sensitivity analysis workflow to improve the computational efficiencies in physiologically-based pharmacokinetic modeling. Frontiers in Pharmacology 2018 Jun; 9:588. 

> Cheng YH, Chou WC, Yang YF, Huang CW, How CM, Chen SC, Chen WY, **Hsieh NH**, Lin YJ, You SH, Liao CM*. PBPK/PD assessment for Parkinson’s disease risk posed by airborne pesticide paraguat exposure. Environmental Science and Pollution Research 2018 Feb; 25(6):5359-68.

2017

> **Hsieh NH**, Lin YJ, Yang YF, Liao CM*. Assessing the oseltamivir-induced resistance risk and implications for influenza infection control strategies. Infection and Drug Resistance 2017 Jul; 10: 215-26.  

> Cheng YH, You SH, Lin YJ, Chen SC, Chen WY, Chou WC, **Hsieh NH**, Liao CM*. Mathematical modeling of postcoinfection with influenza A virus and Streptococcus pneumoniae, with implications for pneumonia and COPD-risk assessment. International Journal of Chronic Obstructive Pulmonary Disease 2017 Jul; 12:1973-88.  

> Lin YJ, Ling MP&ast;, Chen SC, Chen WY, **Hsieh NH**, Cheng YH, You SH, Chou WC, Lin MC, Liao CM&ast;. Mixture risk assessment due to ingestion of arsenic, copper, and zinc from milkfish farmed in contaminated coastal areas. Environmental Science and Pollution Research: 2017 Jun; 24(17):14616-26.  

> **Hsieh NH**, Chung SH, Chen SC, Chen WY, Cheng YH, Lin YJ, You SH, Liao CM*. Anemia risk in relation to lead exposure in lead-related manufacturing. BMC Public Health 2017 May; 17:389.  

2016

> Chen WY*, Chen ZY, **Hsieh NH**, Ju YT. Site-specific water quality criteria for lethal/sublethal protections of freshwater fish exposed to zinc in southern Taiwan. Chemosphere 2016 Sep; 159:412-9.

> Cheng YH, Wang CH, You SH, **Hsieh NH**, Chen WY, Chio CP, Liao CM*. Assessing coughing-induced influenza droplet transmission and implications for infection risk control. Epidemiology and Infection 2016 Jan; 144(2):333-45.

2015

> Chen WY, Cheng YH, **Hsieh NH**, Wu BC, Chou WC, Ho CC, Chen JK, Liao CM\*, Lin P\*. Physiologically-based pharmacokinetic modeling of zinc oxide nanoparticles and zinc nitrate in mice. International Journal of Nanomedicine 2015 Oct; 10:6277-6292.

> Liao CM*, Wu BC, Cheng YH, You SH, Lin YJ, **Hsieh NH**. Ceramics manufacturing contributes to ambient silica air pollution and burden of lung disease. Environmental Science and Pollution Research 2015 Oct; 22(19):15067-79.

> Chen SC, **Hsieh NH**, You SH, Wang CH, Liao CM*. Behavioural response in educated young adults towards influenza A(H1N1)pdm09. Epidemiology and Infection 2015 Jul; 143(9):1846-57.

> Liao CM*, Huang TL, Cheng YH, Chen WY, **Hsieh NH**, Chen SC, Chio CP. Assessing dengue infection risk in southern region of Taiwan and implications for control. Epidemiology and Infection 2015 Apr; 143(5):1059-72.

> Liao CM*, Huang TL, Lin YJ, You SH, Cheng YH, **Hsieh NH**, Chen WY. Regional response of dengue fever epidemics to interannual variation and related climate variability. Stochastic Environmental Research and Risk Assessment 2015 Mar; 29(3):947-58.

2014

> **Hsieh NH**, Cheng YH, Liao CM*. Changing variance and skewness as leading indicators for detecting ozone exposure-associated lung function decrement. Stochastic Environmental Research and Risk Assessment 2014 Dec; 28(8):2205-16. 

> **Hsieh NH**, Liao CM*. In vitro measurement and dynamic modeling-based approaches for deposition risk assessment of inhaled aerosols in human respiratory system. Atmospheric Environment 2014 Oct; 95:268-76.
 
2013

> **Hsieh NH**, Liao CM*. Fluctuations in air pollution give risk warning signals of asthma hospitalization. Atmospheric Environment 2013 Aug; 75:206–16. 

> **Hsieh NH**, Liao CM*. Assessing exposure risk for dust storm events-associated lung function decrement in asthmatics and implications for control. Atmospheric Environment 2013 Apr; 68:256–64. 

2012

> Liao CM*, Cheng YH, Lin YJ, **Hsieh NH**, Huang TL, Chio CP, Chen SC, Ling MP. A Probabilistic transmission and population dynamic model to assess tuberculosis infection risk. Risk Analysis 2012 Aug; 32(8): 1420–32.

> Chio CP, Chen WY, Chou WC, **Hsieh NH**, Ling MP, Liao CM*. Assessing the potential risk to zebrafish posed by environmentally copper and silver nanoparticles. Science of the Total Environment 2012 Mar; 420: 111–8.

> Liao CM*, **Hsieh NH**, Huang TL, Cheng YH, Lin YJ, Chio CP, Chen SC, Ling MP. Assessing trends and predictors of tuberculosis in Taiwan. BMC Public Health 2012 Jan; 12:29.

2011

> Liao CM*, **Hsieh NH**, Chio CP. Fluctuation analysis-based risk assessment for respiratory virus activity and air pollution associated asthma incidence. Science of the Total Environment 2011 Aug; 409: 3325–33.

> Liao CM*, Chio CP, Cheng YH, **Hsieh NH**, Chen WY, Chen SC. Quantitative links between arsenic exposure and influenza A (H1N1) infection-associated lung function exacerbations risk. Risk Analysis 2011 Aug; 31(8): 1281–94.

> Ling MP, Chio CP, Chou WC, Chen WY, **Hsieh NH**, Lin YJ, Liao CM*. Assessing the potential exposure risk and control for airborne titanium dioxide and carbon black nanoparticles in the workplace. Environmental Science and Pollution Research 2011 Jul; 18(6): 877–89.

2010

> Liao CM*, **Hsieh NH**, Chio CP, Chen SC. Assessing the exacerbations risk of influenza-associated chronic occupational asthma. Risk Analysis 2010 Jul; 30(7): 1062–75.

> Liao CM*, Lin TL, **Hsieh NH**, Chen WY. Assessing the arsenic-contaminated rice (Oryza sativa) associated children skin lesions. Journal of Hazardous Materials 2010 Apr; 176(1–3): 239–51.

## Conference Paper

> **Hsieh NH**, Reisfeld B, Chiu WA. pksensi: an R package to apply sensitivity analysis in pharmacokinetic modeling. 58th SOT Annual Meeting, Baltimore, USA, March 10–14, 2019.

> **Hsieh NH**, Reisfeld B, Bois FY, Chiu WA. Applying a global sensitivity analysis workflow to improve computational efficiencies in physiologically-based pharmacokinetic model. 57th SOT Annual Meeting, San Antonio, USA, March 11-15, 2018.

> **Hsieh NH**, Reisfeld B, Bois FY, Chiu WA. Applying A Global Sensitivity Analysis Workflow to Improve Computational Efficiency in Physiologically-Based Pharmacokinetic Modeling. 2017 SRA Annual Meeting, Arlington, USA, December 10-14, 2017. 

> **Hsieh NH**, Chung SH. Meta-Analysis of the Fine Particulate Matters-Associated Occupational Health Risks. SOT 56th Annual Meeting, Baltimore, USA, March 12–16, 2017.

> **Hsieh NH**, Liao CM. Modeling honey bee extinction risk by neonicotinoid insecticide (imidacloprid) exposure. SETAC Europe 26th Annual Meeting, Nantes, France, May 22–26, 2016.

> **Hsieh NH**, Liao CM. Fluctuating air pollution-associated asthma incidence in Taiwan. SETAC Europe 23rd Annual Meeting, Glasgow, UK, May 12–16, 2013.

> **Hsieh NH**, Chio CP, Liao CM. Assessing the risks for aquatic organisms posed by waterborne copper and silver nanoparticles. SETAC Europe 21st Annual Meeting Milan, Italy, May 15–19, 2011.
